In [2]:
import pandas as pd
%matplotlib inline
#from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import numpy as np

In [3]:
data_gh_p="/Users/orsi/Dropbox/behance-data/NEW_ANALYSIS/data/github/"
data_bh_p="/Users/orsi/Dropbox/behance-data/NEW_ANALYSIS/data/behance/"

In [4]:
data_gh=pd.read_csv(data_gh_p+"topsamples60d10P_allsample01_20181018_3.csv")

/Users/orsi/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (0,74) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
data_gh

,Unnamed: 0,Backend,DT_class,DT_class_n10,DT_class_n100,DT_class_n20,DT_class_n5,DT_class_n50,Data_Science,Frontend,...,pushes,reposwhereactive,still_active,successcollabrepos,successownrepos,total_langs,userlogin,year,femaleness_2_new,femaleness_2_following
0,annuh,0.384896,14,18,129,17,4,80,-2.225391,-4.268793,...,83,18,1.0,0,0,17.0,annuh,2013,0.530618,0.453065
1,sophiecooper,-0.846120,23,9,69,38,7,62,0.198805,0.127745,...,109,25,1.0,0,0,24.0,sophiecooper,2014,0.339680,0.513774
2,nuancesb,-1.818602,19,14,197,30,4,65,-1.703758,1.318626,...,161,28,1.0,0,0,16.0,nuancesb,2014,0.781397,0.870798
3,mobula,0.197222,14,18,130,17,4,80,21.008867,6.929481,...,117,29,1.0,0,0,61.0,mobula,2013,0.460428,0.490026
4,SophieMuspratt,6.538069,8,15,179,30,3,92,-2.443498,-5.227910,...,66,22,1.0,0,0,15.0,SophieMuspratt,2014,0.433139,0.425469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29995,16.525843,8,15,153,30,3,69,-2.845902,-5.959453,...,273,34,1.0,0,0,25.0,29995,2015,0.454406,0.423607
29996,29996,-2.164406,19,17,84,18,4,73,2.002841,-5.533023,...,127,14,1.0,0,0,5.0,29996,2013,0.377385,0.364072
29997,29997,1.660313,4,15,193,23,3,91,-2.023175,-6.196384,...,32,13,1.0,0,0,7.0,29997,2013,0.466112,0.472224
29998,29998,9.563659,4,16,194,30,3,68,-2.567807,-6.241514,...,46,18,1.0,0,0,13.0,29998,2013,0.454913,0.416127
29999,29999,-2.368203,4,15,193,10,3,91,-1.929884,-6.176810,...,58,13,0.0,0,0,0.0,29999,2015,0.493973,0.477048

In [6]:
data_bh=pd.read_csv(data_bh_p+"sample1_with_femaleness_PCA_survival_contributors.csv")

In [7]:
data_bh.head()

,user_id,fields,followers,following,username,gender,country,comments,project_counts,project_views,...,Advertising,gender_female,gender_male,femaleness_2_new,last_activity,survival,user_id.1,survival2,survivial_clean,number_of_contributors
0,4275179,Graphic Design|Art Direction|Illustration,36,311,guillermotheill,male,Argentina,9,13,948,...,2.247709,0,1,0.357656,2018-06-05 17:45:49,1.0,4275179,1,1,2.0
1,94389,Photography|Fine Arts|Photojournalism,802,262,ijazz,male,France,820,79,79762,...,0.905654,0,1,0.485360,2018-09-29 21:39:18,1.0,94389,1,1,0.0
2,52539,Art Direction|Illustration|Graphic Design,4139,2786,akaempk,male,Spain,362,86,282573,...,-9.585884,0,1,0.250185,2016-05-05 07:58:55,0.0,52539,0,1,1.0
3,4831337,Illustration|Graphic Design|Advertising,115,1946,angelo_at,male,Peru,2,13,3446,...,0.916329,0,1,0.281127,2018-01-29 20:01:29,1.0,4831337,1,1,2.0
4,93415,Pattern Design|Textile Design|Print Design,615,593,keenlight,male,Russian Federation,574,4,1072,...,-0.314546,0,1,0.324069,2014-01-22 17:47:46,0.0,93415,0,1,0.0

In [14]:
data_gh[[ 'PRc', 'PRm', 'PRo',"year",
       'collaborators','pushes', 'n_repos', 'reposwhereactive',"following" ,'following','collaborators',
        'L_C', 'L_CSS', 'L_CoffeeScript', 'L_Cplusplus', 'L_Csharp',
       'L_Go', 'L_HTML', 'L_Java', 'L_JavaScript', 'L_Jupyter_Notebook',
       'L_Lua', 'L_ObjectiveC', 'L_PHP', 'L_Perl', 'L_Python', 'L_R', 'L_Ruby',
       'L_Scala', 'L_Shell', 'L_Swift', 'L_TeX', 'L_TypeScript', 'L_VimL',
       'L_other_langs',]]

,PRc,PRm,PRo,year,collaborators,pushes,n_repos,reposwhereactive,following,following,...,L_Python,L_R,L_Ruby,L_Scala,L_Shell,L_Swift,L_TeX,L_TypeScript,L_VimL,L_other_langs
0,3.0,2.0,7.0,2013,3,83,7,18,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0
1,4.0,3.0,5.0,2014,11,109,10,25,1.0,1.0,...,2.0,0.0,7.0,0.0,0.0,7.0,0.0,0.0,0.0,2.0
2,1.0,1.0,2.0,2014,5,161,23,28,5.0,5.0,...,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2.0,1.0,8.0,2013,2,117,7,29,3.0,3.0,...,24.0,0.0,1.0,0.0,6.0,0.0,0.0,0.0,0.0,3.0
4,1.0,1.0,1.0,2014,2,66,19,22,3.0,3.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,0.0,0.0,1.0,2015,2,273,32,34,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
29996,3.0,3.0,4.0,2013,4,127,8,14,25.0,25.0,...,4.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29997,0.0,0.0,0.0,2013,4,32,7,13,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
29998,0.0,0.0,0.0,2013,1,46,17,18,9.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
29999,0.0,0.0,0.0,2015,1,58,12,13,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
24

Index(['user_id', 'fields', 'followers', 'following', 'username', 'gender',
       'country', 'comments', 'project_counts', 'project_views',
       'project_appreciations', 'project_comments', 'created_on', 'created2',
       'tenure', 'appreciate', 'total_activity', 'graphic_design',
       'illustration', 'branding', 'art_direction', 'digital_art',
       'photography', 'advertising', 'drawing', 'typography', 'print_design',
       'web_design', 'character_design', 'editorial_design', 'fashion',
       'packaging', 'fine_arts', 'digital_photography', 'painting',
       'creative_direction', 'animation', 'ui_ux', 'product_design',
       'architecture', 'motion_graphics', 'cartooning', 'interaction_design',
       'retouching', 'icon_design', 'industrial_design', 'interior_design',
       'music', 'film', 'calligraphy', 'design', 'crafts', 'visual_effects',
       'game_design', 'exhibition_design', 'pattern_design', 'sculpting',
       'furniture_design', 'copywriting', 'computer_animation',
       'web_development', 'fashion_styling', 'textile_design',
       'cinematography', 'photojournalism', 'street_art', 'landscape_design',
       'automotive_design', 'Photography', 'Graphic_Design', 'Branding',
       'Art_Direction', 'Digital_Art', 'Fashion_Photography', 'Fine_Arts',
       'Web_design_UX', 'Advertising', 'gender_female', 'gender_male',
       'femaleness_2_new', 'last_activity', 'survival', 'user_id.1',
       'survival2', 'survivial_clean', 'number_of_contributors'],
      dtype='object')

In [ ]:
bh_cs=['total_activity', 'project_counts','comments', "following",'project_views','project_appreciations',
       'tenure', "total_activity",
       'graphic_design',
       'illustration', 'branding', 'art_direction', 'digital_art',
       'photography', 'advertising', 'drawing', 'typography', 'print_design',
       'web_design', 'character_design', 'editorial_design', 'fashion',
       'packaging', 'fine_arts', 'digital_photography', 'painting',
       'creative_direction', 'animation', 'ui_ux', 'product_design',
       'architecture', 'motion_graphics', 'cartooning', 'interaction_design',
       'retouching', 'icon_design', 'industrial_design', 'interior_design',
       'music', 'film', 'calligraphy', 'design', 'crafts', 'visual_effects',
       'game_design', 'exhibition_design', 'pattern_design', 'sculpting',
       'furniture_design', 'copywriting', 'computer_animation',
       'web_development', 'fashion_styling', 'textile_design',
       'cinematography', 'photojournalism', 'street_art', 'landscape_design',
       'automotive_design',
        "gender_female"]